# Generated by Django 5.1.3 on 2024-11-06 16:23

import child_app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parent_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='child_app_user', serialize=False, to='parent_app.user')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('parent_app.user',),
            managers=[
                ('objects', child_app.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=400)),
                ('quantity', models.IntegerField(default=0)),
                ('users', models.ManyToManyField(blank=True, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
